Repository githMedinaGto/WebSecureBookings, pull requests merged in 2023-08, with the labels that each got.

#18 Se agrega la funcionalidad de Token
  App_Data/Token/ConsumirToken.cs
  App_Data/Token/GenerarToken.cs
Labels: documentation

#19 Samuel
  App_Data/Controllers/Autenticacion/AutenticacionController.cs
  App_Data/Controllers/Autenticacion/Autorizacion.cs
  App_Data/Models/DB.edmx.diagram
  App_Data/Models/Dia/DiaModel.cs
  App_Data/Models/sysdiagrams.cs
  App_Data/Models/tUsuario.cs
  Scripts/Css/RegistroUsuarios.css
  Views/Autenticacion/RegistroUsuarios.aspx
  Views/Autenticacion/RegistroUsuarios.aspx.cs
  Views/Autenticacion/RegistroUsuarios.aspx.designer.cs
  Views/Autenticacion/RegistroUsuarios.js
Labels: documentation, enhancement

#20 Alexander
  Views/PerfilUsuario/PerfilUsuario.aspx
  Views/PerfilUsuario/PerfilUsuario.aspx.cs
  Views/PerfilUsuario/PerfilUsuario.aspx.designer.cs
  Web.config
  WebSecureBookings.csproj
  packages.config
Labels: documentation

#21 Se suben al archivo .csproj
  App_Data/Models/DB.Context.cs
  WebSecureBookings.csproj
Labels: enhancement

#25 Se agrega la funcionalidad de generar el menu y la validación del tok…
  Master.Master
  Master.Master.cs
  Master.Master.designer.cs
  WebSecureBookings.csproj
Labels: documentation, duplicate

#26 Andres
  App_Data/Controllers/Token/GenerarToken.cs
  App_Data/Controllers/VistaCitas/VistaCitasController.cs
  App_Data/Models/ActaConfirmacionCita/ActaModel.cs
  Views/VistaCitas/VistaCitas.aspx
  Views/VistaCitas/VistaCitas.aspx.cs
  Views/VistaCitas/VistaCitas.js
Labels: documentation, enhancement
